#!/bin/csh
#SBATCH --job-name NISE3
#SBATCH --nodes=1
#SBATCH --ntasks=1

setenv OMP_NUM_THREADS 1
setenv MKL_NUM_THREADS 1
echo $MKL_NUM_THREADS

setenv WD $SLURM_SUBMIT_DIR

echo $TMPDIR
cd $TMPDIR

cp $WD/run $TMPDIR
cp $WD/inp* $TMPDIR
cp $WD/stochastic $TMPDIR

./run

~/program/NISE_2015/NISE3/translate inpTra
time ~/program/NISE_2015/NISE3/NISE3 input1D

cp *.log $WD
cp *.dat $WD
